{{- if .Values.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
  {{- with .Values.namespace.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
    {{- include "application-bootstrap.labels" . | nindent 4 }}
  
  {{- with .Values.namespace.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
