{{- if .Values.role.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "application-bootstrap.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- with .Values.role.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- include "application-bootstrap.labels" . | nindent 4 }}
  {{- with .Values.role.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.role.rules }}
rules:
  {{- toYaml . | nindent 2 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "application-bootstrap.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- with .Values.role.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- include "application-bootstrap.labels" . | nindent 4 }}
  {{- with .Values.role.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "application-bootstrap.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "application-bootstrap.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
