{{- if .Values.secretproviderclass.create -}}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ include "application-bootstrap.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "application-bootstrap.labels" . | nindent 4 }}
{{- with .Values.secretproviderclass.spec }}
spec:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
